### ISSUE TITLE
only first page scraped

### ISSUE THREAD

**Issue by monaejam** [epctex/bbb-scraper#2]
it only scrape the very first page

**Comment by tugkan** [comment]
Hey there!

Thank you very much for using our actor and letting us know about your inquiry. Can you please share your Run ID? It seems everything works properly on our end, but there can be something that we can miss.

Best

**Comment by monaejam** [comment]
Yes , here is the ID : iSE2IYidxfXunwikB
My input has lots of review and I am not determining any end page but it does not scrape all the pages

**Comment by tugkan** [comment]
Hey @monaejam ! Just checked your run and it seems like there is a bug on the actor. Sorry for the inconvenience. I think in a day or two, we can resolve this problem. I'll keep the issue open and will let you know asap.

**Comment by monaejam** [comment]
that would be great cause I want to subscribe and I put it on hold. It
would be great if it gets fixed quickly.
Best Regards,
Mona Jam

**Comment by tugkan** [comment]
Hey @monaejam !

Thank you very much for waiting. The bug has been resolved and the updated version is deployed on Apify Platform. Please use the latest version for the best experience.

Best
